#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail


if [ -f .env ]
then
  source .env
fi

# define tasks here
init (){
  if [ ! -d venv ]
  then
    python -m venv venv
    source venv/bin/activate
    pip install -U pip
    pip install -r requirements.txt
  fi
  source venv/bin/activate
}

tests () {
  export AWS_ACCESS_KEY_ID='testing'
  export AWS_SECRET_ACCESS_KEY='testing'
  export AWS_SECURITY_TOKEN='testing'
  export AWS_SESSION_TOKEN='testing'
  init
  pip install -r requirements.test.txt
  python -m pytest -sv --disable-warnings --cov=vapor tests/ && coverage report -m && coveralls
}

clean () {
  rm -rf vapor.egg-info build dist
}

lint () {
  init
  pip install -r requirements.test.txt
  pylint vapor
}

list () {
  grep -E "()\ ?{$" "$0" | grep -v 'grep ' | awk '{print $1}' | sort
}

# main start here
command=${1:-""}

if [[ -n $(type -t "${command}") ]] && [[ $(type -t "${command}") = function ]]
then
  shift
  eval "$command" "$@"
  exit $?
fi

case "$command" in
  *)
    list
esac
