#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail


if [ -f .env ]
then
  source .env
fi

tests () {
  export AWS_ACCESS_KEY_ID='testing'
  export AWS_SECRET_ACCESS_KEY='testing'
  export AWS_SECURITY_TOKEN='testing'
  export AWS_SESSION_TOKEN='testing'
  export AWS_DEFAULT_REGION='testing'
  poetry run pytest -sv -vv --cov=vapor tests/
  poetry run coverage report -m
  # Github actions will setup CI
  if [ "${CI:-}" = "true" ]
  then
    poetry run coveralls
  fi
}

lint () {
  poetry run pylint vapor tests
}

clean () {
  rm -rf vapor.egg-info build dist
}

list () {
  grep -E "()\ ?{$" "$0" | grep -v 'grep ' | awk '{print $1}' | sort
}

# main start here
command=${1:-""}

if [[ -n $(type -t "${command}") ]] && [[ $(type -t "${command}") = function ]]
then
  shift
  eval "$command" "$@"
  exit $?
fi

case "$command" in
  *)
    list
esac
