name: build
on: [push]

jobs:
  build:
    name: Lint/Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Black
        uses: lgeiger/black-action@master
      - name: Pylint
        run: ./manage lint
      - name: Test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}
        run: ./manage tests
  publish:
    needs: build
    if: github.ref == 'refs/heads/master' && github.repository == 'xiaket/vapor'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install poetry
      - name: Build
        run: poetry build
      - name: Publish to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token_vapor }}
        run: poetry --build publish
