name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
    name: Lint/Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.3.1
      - name: set venv
        run: poetry env use python${{ matrix.version }}
      - name: install packages
        run: poetry install
      - name: Pylint
        run: ./manage lint
      - name: Test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}
        run: ./manage tests

  publish:
    needs: build
    if: github.ref == 'refs/heads/main' && github.repository == 'xiaket/vapor'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install poetry
      - name: Publish to pypi
        run: poetry publish --build --username=__token__ --password=${{ secrets.pypi_token_vapor }}
        continue-on-error: true
